security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        my_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: my_provider

            logout:
                path: logout
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                # where to redirect after logout
                # target: app_any_route
            remember_me:
                name: SECURITY_DEMO
                secret: '%kernel.secret%'
                lifetime: 604800



    access_control:
    # !!! Comment this to change authentication of the site !!!
     - { path: ^(?!/(login|register)), roles: ROLE_USER }
    # !!! Comment this to change authentication of the site !!!


        # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }